# Generated by Django 3.2.7 on 2021-09-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
