# Generated by Django 3.2.7 on 2021-09-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='friends',
        ),
        migrations.AddField(
            model_name='chat',
            name='chatName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
