# Generated by Django 3.2.7 on 2021-09-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210927_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chatImg',
            field=models.ImageField(blank=True, default='chat.png', null=True, upload_to=''),
        ),
    ]
