# Generated by Django 3.2.7 on 2021-09-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chat_chatimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatImg',
            field=models.ImageField(blank=True, default='chat.jpg', null=True, upload_to=''),
        ),
    ]
