# Generated by Django 3.2.7 on 2021-09-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_chat_chatimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile_pic',
            field=models.ImageField(default='profile1.png', null=True, upload_to=''),
        ),
    ]
